services:
  api:
    build:
      context: ./api
      dockerfile: test.dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/oncology-quest
      HOST_PORT: 8000
      HOST_IP: 0.0.0.0
      JWT_SECRET: testsecret69420
    ports:
      - "8000:8000"
    depends_on:
      - db
  api-integration-tests:
    build:
      context: ./integration-tests
      dockerfile: dockerfile
    depends_on:
      - api
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oncology-quest
    ports:
      - "5433:5432"