version: "3.8"
services:
  api:
    build:
      context: ./oncology-quest-api
      dockerfile: dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/oncology-quest
      HOST_PORT: 8000
      HOST_IP: 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db
  api-integration-tests:
    build:
      context: ./oncology-quest-api-integration-tests
      dockerfile: dockerfile
    depends_on:
      - api
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oncology-quest
    ports:
      - "5433:5432"